
pipeline:
	inkscape -D svg/1_fetch_instruction_cycle_pipeline_v2_info.svg -o 1_fetch_info.png --export-type="png"
	inkscape -D svg/2_exec_instruction_cycle_pipeline_v2_info.svg -o 2_exec_ins_info.png --export-type="png"
	inkscape -D svg/3_exec_dst_instruction_cycle_pipeline_v2_info.svg -o 3_exec_dst_info.png --export-type="png"
	inkscape -D svg/4_exec_add_jumpinstruction_cycle_pipeline_v2_info.svg -o 4_exec_add_jump_info.png --export-type="png"
	inkscape -D svg/5_exec_jump_branch_instruction_cycle_pipeline_v2_info.svg -o 5_exec_jump_branch_info.png --export-type="png"
	inkscape -D svg/6_reg_data_instruction_cycle_pipeline_v2_info.svg -o 6_write_reg_data.png --export-type="png"
